package io.github.picocrypt_ng.picocrypt_ng.ui.components

import android.content.ContentResolver
import android.content.Context
import android.content.res.Resources
import android.net.Uri
import io.github.picocrypt_ng.picocrypt_ng.R
import io.mockk.every
import io.mockk.mockk
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.IOException
import java.io.InputStream
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import kotlin.coroutines.ContinuationInterceptor
import kotlin.io.path.createTempDirectory
import kotlin.coroutines.cancellation.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

class NewKeyfileCreationTest {
    @Test
    fun `production creation calls the IO-safe copy service without an outer dispatcher boundary`() = runTest {
        val context = mockk<Context>()
        val resources = mockk<Resources>()
        val resolver = mockk<ContentResolver>()
        val uri = mockk<Uri>()
        val writtenBytes = ByteArrayOutputStream()
        val keyfileBytes = ByteArray(32) { 0x5A.toByte() }
        val callerInterceptor = currentCoroutineContext()[ContinuationInterceptor]
        var copyInterceptor: ContinuationInterceptor? = null
        every { context.contentResolver } returns resolver
        every { resolver.openOutputStream(uri) } returns writtenBytes

        val result = createAndCopyKeyfile(
            context = context,
            resources = resources,
            uri = uri,
            keyfileIndex = 0,
            randomBytes = keyfileBytes,
            copyKeyfile = { _, _, _ ->
                copyInterceptor = currentCoroutineContext()[ContinuationInterceptor]
                Result.success("/internal/keyfile_0")
            },
        )

        assertTrue("The injected production copy should succeed", result.isSuccess)
        assertSame(
            "An outer IO dispatcher would add a cancellation boundary after the service published its file",
            callerInterceptor,
            copyInterceptor,
        )
        assertEquals(32, writtenBytes.size())
        assertTrue("The direct caller path must still zero generated bytes", keyfileBytes.all { it == 0.toByte() })
    }

    @Test
    fun `production keyfile creation zeroes bytes and leaves no file when cancelled`() = runTest {
        val filesDir = createTempDirectory("picocrypt-new-keyfile").toFile()
        val context = mockk<Context>()
        val resources = mockk<Resources>()
        val resolver = mockk<ContentResolver>()
        val uri = mockk<Uri>()
        val writtenBytes = ByteArrayOutputStream()
        val waitingAtEndOfInput = CountDownLatch(1)
        val allowInputToFinish = CountDownLatch(1)
        val keyfileBytes = ByteArray(32) { 0x5A.toByte() }
        val source = object : InputStream() {
            private var offset = 0

            override fun read(): Int = error("copyTo should use the bulk-read override")

            override fun read(buffer: ByteArray, bufferOffset: Int, length: Int): Int {
                val sourceBytes = writtenBytes.toByteArray()
                if (offset < sourceBytes.size) {
                    val copied = minOf(length, sourceBytes.size - offset)
                    sourceBytes.copyInto(buffer, bufferOffset, offset, offset + copied)
                    offset += copied
                    return copied
                }
                waitingAtEndOfInput.countDown()
                check(allowInputToFinish.await(5, TimeUnit.SECONDS)) {
                    "Test did not release the generated-keyfile source"
                }
                return -1
            }
        }
        every { context.filesDir } returns filesDir
        every { context.contentResolver } returns resolver
        every { context.getString(R.string.error_copy_failed) } returns "Copy failed"
        every { resources.getString(R.string.keyfile_write_failed) } returns "Write failed"
        every { resolver.openOutputStream(uri) } returns writtenBytes
        every { resolver.openInputStream(uri) } returns source

        try {
            val creation = async(Dispatchers.Default) {
                createAndCopyKeyfile(
                    context = context,
                    resources = resources,
                    uri = uri,
                    keyfileIndex = 0,
                    randomBytes = keyfileBytes,
                )
            }
            assertTrue(
                "The real creation path should reach the final blocking read",
                waitingAtEndOfInput.await(5, TimeUnit.SECONDS),
            )

            val cancellation = CancellationException("cancel generated keyfile copy")
            creation.cancel(cancellation)
            allowInputToFinish.countDown()

            try {
                creation.await()
                fail("CancellationException must be rethrown")
            } catch (actual: CancellationException) {
                assertEquals(cancellation.message, actual.message)
            }

            assertTrue(
                "Every generated keyfile byte must be zeroed by the production path",
                keyfileBytes.all { it == 0.toByte() },
            )
            val internalDir = File(filesDir, "picocrypt_files")
            assertTrue(
                "Cancelled creation must leave no internal keyfile artifacts",
                internalDir.listFiles().isNullOrEmpty(),
            )
        } finally {
            allowInputToFinish.countDown()
            filesDir.deleteRecursively()
        }
    }

    @Test
    fun `configuration cancellation never reaches the error owner`() = runTest {
        val thrownCancellation = CancellationException("thrown cancellation")
        val returnedCancellation = CancellationException("returned cancellation")
        val cancellations = listOf(
            thrownCancellation to suspend {
                throw thrownCancellation
            },
            returnedCancellation to suspend {
                Result.failure<String>(returnedCancellation)
            },
        )

        cancellations.forEach { (expected, operation) ->
            val errors = mutableListOf<Throwable>()

            try {
                runNewKeyfileCreation(
                    operation = operation,
                    onSuccess = { fail("Cancelled keyfile creation must not succeed") },
                    onFailure = { errors += it },
                )
                fail("CancellationException must be rethrown")
            } catch (actual: CancellationException) {
                assertSame(expected, actual)
            }

            assertEquals("Cancellation must not become a user-visible error", emptyList<Throwable>(), errors)
        }
    }

    @Test
    fun `copy and create failures each reach one error owner exactly once`() = runTest {
        val copyFailure = IOException("copy failed")
        val createFailure = SecurityException("create failed")
        val failures = listOf(
            copyFailure to suspend { Result.failure<String>(copyFailure) },
            createFailure to suspend { throw createFailure },
        )

        failures.forEach { (expected, operation) ->
            val errors = mutableListOf<Throwable>()

            runNewKeyfileCreation(
                operation = operation,
                onSuccess = { fail("Failed keyfile creation must not succeed") },
                onFailure = { errors += it },
            )

            assertEquals("A failure must have one dialog state owner", 1, errors.size)
            assertSame(expected, errors.single())
        }
    }

    @Test
    fun `successful creation bypasses the error owner`() = runTest {
        val errors = mutableListOf<Throwable>()
        var createdPath: String? = null

        runNewKeyfileCreation(
            operation = { Result.success("/internal/keyfile_0") },
            onSuccess = { createdPath = it },
            onFailure = { errors += it },
        )

        assertEquals("/internal/keyfile_0", createdPath)
        assertEquals(emptyList<Throwable>(), errors)
    }
}
